# Generated by Django 3.2 on 2022-05-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('DN', 'Done')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
