# Generated by Django 3.2 on 2022-05-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MNGR', 'Manager'), ('DEV', 'Developer'), ('ACC', 'ACCOUNTER')], default='DEV', max_length=32),
            preserve_default=False,
        ),
    ]
